DROP DATABASE TRAVEL_TRAILS;
CREATE DATABASE TRAVEL_TRAILS;
GRANT ALL ON TRAVEL_TRAILS.* TO 'sriram'@'localhost'  IDENTIFIED BY 'project123';

CREATE TABLE REVIEW(
REVIEW_NUM INT AUTO_INCREMENT PRIMARY KEY ,
REVIEWER VARCHAR(30) UNIQUE NOT NULL ,
LOCATION VARCHAR(200) NOT NULL ,
COUNTRY VARCHAR(50),
DATEVISITED DATE,
THEREVIEW VARCHAR(5000),
HYGIENE INT,
HOSPITALITY INT,
PRICING INT,
FOOD INT,
IMAGE BLOB
);

CREATE TABLE USER(
	USEREMAIL VARCHAR(50),
	PASSWORD VARCHAR(50)
);



